name: "Unit Testing"
on: [ push ]

jobs:
  build:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Set up Go"
        uses: actions/setup-go@v2
        with:
          go-version: "1.15"
      - run: make testing
